HEADERS = {
    'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Mobile Safari/537.36'}
BROWSER_ONLY = 'BROWSER_ONLY'
AUTO_ATC = 'AUTOMATE_ATC'
NOTHING = 'NOTHING'
WIDGETS_P_THREAD = 4

RESIZABLE_WIDTH = False
RESIZABLE_HEIGHT = True

WIDGET_VGAP = (0, 10)
WIDGET_HGAP = (0, 10)

BTN_WIDTH = 15
STOCK_WIDTH = 15
P_NAME_WIDTH = 15
MESSAGE_WIDTH = 30


STEP_SIZE = 250
SCALE_SKIP = 1_000
SCALE_MIN = 1_000
SCALE_MAX = 10_000

SOLD_OUT = 'SOLD_OUT'
IN_STOCK = 'IN_STOCK'
NOT_NEARBY = 'NOT_NEARBY'
UNKNOWN = 'UNKNOWN'
ERROR = 'ERROR'

APP_XPAD = 10
APP_YPAD = 10
APP_GEO = f"{795}x{600}"
APP_BUTTON_COLOR = 'BLACK'
APP_BACKGROUND_COLOR = 'BLACK'
APP_TEXT_COLOR = '#E3E3E3'
APP_TEXT_FONT = 'TkDefaultFont'
APP_LABEL_FONT = 'HELVETICA 9 bold'

STK_WDT_VGAP = (0, 10)
STK_WDT_FG = 'WHITE'
STK_WDT_BORCOL = '#DCD8D8'
STK_WDT_SLT_CLR = '#555555'
STK_WDT_CLK_CLR = 'BLACK'


# NEED TO ADJUST THESE THREE
SELENIUM_PROFILE_PATH = r"C:\Users\fsoto\AppData\Local\Google\Chrome\Selenium"
SELENIUM_PROFILE_NAME = "Profile 4"
CHROMEDRIVER_PATH = r'D:\Documents HDD\Workstations\Python\StockCheckerGUI\Driver\chromedriver.exe'